[darwin]
match = "pawnc-(.+)-(darwin|macos)\\.zip"
method = "zip"
binary = "pawncc"

[darwin.paths]
"(pawnc-(.+)/)?bin/pawncc" = "pawncc"
"(pawnc-(.+)/)?lib/libpawnc.dylib" = "libpawnc.dylib"

[linux]
match = "pawnc-(.+)-(linux)\\.tar\\.gz"
method = "tgz"
binary = "pawncc"

[linux.paths]
"(pawnc-(.+)/)?bin/pawncc" = "pawncc"
"(pawnc-(.+)/)?lib/libpawnc.so" = "libpawnc.so"

[windows]
match = "pawnc-(.+)-(windows)\\.zip"
method = "zip"
binary = "pawncc.exe"

[windows.paths]
"(pawnc-(.+)/)?bin/pawnc.dll" = "pawnc.dll"
"(pawnc-(.+)/)?bin/pawncc.exe" = "pawncc.exe"

[android-arm32]
match = "pawnc-(.+)-(android)-(arm32)\\.zip"
method = "zip"
binary = "pawncc"

[android-arm32.paths]
"(pawnc-(.+)/)?bin/pawncc" = "pawncc"
"(pawnc-(.+)/)?lib/libpawnc.so" = "libpawnc.so"

[android-arm64]
match = "pawnc-(.+)-(android)-(arm64)\\.zip"
method = "zip"
binary = "pawncc"

[android-arm64.paths]
"(pawnc-(.+)/)?bin/pawncc" = "pawncc"
"(pawnc-(.+)/)?lib/libpawnc.so" = "libpawnc.so"